### PR TITLE
Added roll

### PR DESCRIPTION
**Pull request by PriyamJChakrabarty**
## Issue: #111

Added Rolling Text Animation

### CODE REVIEW

**Comment by Tanisha-Puri** [comment]
You haven't added your figma file in the txt file, it is empty

**Comment by PriyamJChakrabarty** [comment]
@Tanisha-Puri OK Sorry, but I couldn't check the comment cause I slept early and now the issue is closed.........can something be done about it?

**Comment by Tanisha-Puri** [comment]
Ok, i have reopened this PR, just add your figma file in this

**Comment by PriyamJChakrabarty** [comment]
OK thanks!

**Comment by PriyamJChakrabarty** [comment]
@Tanisha-Puri commited the txt.....pls check

**Pull request merged**
