### PR TITLE
Created very good design

### PR DESCRIPTION
**Pull request by puravimohta15**
Issue: #86 
Added figma link and explanation

### CODE REVIEW

**Comment by Tanisha-Puri** [comment]
The colour scheme is not very pleasing and completely different from the original one. The navigation icons and scrollbars are not looking very good. Else, it was a good try. Keep contributing!

**Comment by puravimohta15** [comment]
In the post it was mentioned we could change the colour scheme.

**Comment by Tanisha-Puri** [comment]
Yes, you could change the colour scheme but it the colours you used like purple were not much suitable as it does not come under either light or dark and it was very vibrant. Your design was fine but in a competitive issue, only best 3 designs are merged.

**Comment by puravimohta15** [comment]
Will we receive partial points for trying?
Yaar 3 baje tak banaya tha😭

**Comment by Tanisha-Puri** [comment]
Best 3 me partial points the
1st-50
2nd-40
3rd-30
I understand your hardwork but i am bound to only 3. You could try on next tasks.

**Pull request closed without merging**
