### PR TITLE
Create Suvanwita.txt

### PR DESCRIPTION
**Pull request by Suvanwita**
Issue: #29 
Added bouncing ball figma file link

### CODE REVIEW

**Comment by Tanisha-Puri** [comment]
It seems like you have taken your work from community as your version history is not looking fine

**Comment by Suvanwita** [comment]
Actually I had previously made one bouncing ball animation with 8 frames
This is the link to the same
https://www.figma.com/design/tzr5emIz3wA0MnaZNXevwN/Untitled?node-id=0-1&p=f&t=KtON0ncMoSSDCteG-0

But then I wanted to increase the number of frames so I copied it and then
worked on the copied file to increase the number of frames.
This was the link for the second file:
https://www.figma.com/design/EtOgr4z0d32E0EHMaUxg1n/Bouncing-ball?node-id=0-1&p=f&t=1YNUGTrTvfCpDQxB-0

I had not used the one in the community but my own one. I sincerely
apologise for the confusion. Please inform me if I should make a new pull
request.

Thank You,
Suvanwita Das
(IIT2024013)

**Comment by Tanisha-Puri** [comment]
Ok, thanks for clarification, no need to make another PR, i have merged this one

**Comment by Suvanwita** [comment]
Thank you ma'am

**Pull request merged**
