### PR TITLE
Added the theme

### PR DESCRIPTION
**Pull request by PriyamJChakrabarty**
## Description

Added the theme change

### CODE REVIEW

**Review by Tanisha-Puri — COMMENTED** [review]
Can you please fork the repo directly from github for now, then it will not show the issue of the folder name, i will later change the name so that no conflicts occur

**Comment by PriyamJChakrabarty** [comment]
Wait, everything is fine right?

**Comment by PriyamJChakrabarty** [comment]
Or are there any conflicts?

**Comment by Tanisha-Puri** [comment]
Yes, it's fine now

**Pull request merged**
